# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e50118d94324656b96b844c78b24f759c4a673d89a28512d35f90ed4f62b0d0e79db5191e69acdc6b2b2b539498601f19fa65f15d43711091849463f94e9474d

test:
  secret_key_base: 073b29dd2afaf0a0524e55afca5a60d4ef0b5e51525efe180a30f8017a1e3a2a92d7a2fa375b479b2c34ee7593d5da67a3c8ad1d6db92f9a8bf3e41ec05b6590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
